const fs = require('fs');
const lines = [];
const a = s => lines.push(s);

a("@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap');");
a("");
a("*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }");
a("");
a(":root {");
a("  --primary:  #00B5A5;");
a("  --dark:     #007A6E;");
a("  --mid:      #009B8D;");
a("  --light:    #E8F7F5;");
a("  --border:   #DFF0EE;");
a("  --white:    #ffffff;");
a("  --bg:       #F5FAF9;");
a("  --text:     #0D1F1E;");
a("  --muted:    #4E706C;");
a("  --soft:     #8FADA9;");
a("  --shadow:   0 1px 2px rgba(0,0,0,0.04), 0 4px 16px rgba(0,0,0,0.07);");
a("  --shadow-md:0 2px 4px rgba(0,0,0,0.06), 0 8px 28px rgba(0,0,0,0.1);");
a("  --radius:   14px;");
a("  --radius-sm:8px;");
a("}");
a("");
a("body {");
a("  font-family: 'Inter', sans-serif;");
a("  background: var(--bg);");
a("  color: var(--text);");
a("  min-height: 100vh;");
a("  -webkit-font-smoothing: antialiased;");
a("}");
a("");
a("/* ── TOPNAV ── */");
a(".topnav {");
a("  background: linear-gradient(135deg, #005F56 0%, var(--dark) 50%, #00897B 100%);");
a("  height: 64px;");
a("  display: flex; align-items: center;");
a("  padding: 0 48px; gap: 18px;");
a("  position: sticky; top: 0; z-index: 100;");
a("  box-shadow: 0 2px 20px rgba(0,0,0,0.22);");
a("}");
a(".topnav::after {");
a("  content: '';");
a("  position: absolute; bottom: 0; left: 0; right: 0;");
a("  height: 2px;");
a("  background: linear-gradient(90deg, var(--primary), transparent);");
a("  opacity: 0.6;");
a("}");
a(".topnav-divider { width: 1px; height: 24px; background: rgba(255,255,255,0.15); }");
a(".topnav-title { color: #fff; font-size: 14.5px; font-weight: 700; letter-spacing: 0.1px; }");
a(".topnav-sub { color: rgba(255,255,255,0.45); font-size: 11px; margin-top: 1px; }");
a("");
a("/* ── STEP BAR ── */");
a(".step-bar {");
a("  background: var(--white);");
a("  border-bottom: 1px solid var(--border);");
a("  display: flex; align-items: center; justify-content: center;");
a("  height: 56px; gap: 0;");
a("  box-shadow: 0 1px 8px rgba(0,0,0,0.04);");
a("}");
a(".step-item {");
a("  display: flex; align-items: center; gap: 10px;");
a("  padding: 0 24px; height: 100%;");
a("  font-size: 12.5px; font-weight: 600;");
a("  color: var(--soft);");
a("  cursor: default;");
a("  position: relative;");
a("  transition: color 0.2s;");
a("}");
a(".step-item.active { color: var(--dark); }");
a(".step-item.active::after {");
a("  content: '';");
a("  position: absolute; bottom: 0; left: 24px; right: 24px;");
a("  height: 2.5px;");
a("  background: linear-gradient(90deg, var(--primary), var(--dark));");
a("  border-radius: 2px 2px 0 0;");
a("}");
a(".step-item.done { color: var(--muted); }");
a(".step-num {");
a("  width: 22px; height: 22px; border-radius: 50%;");
a("  display: flex; align-items: center; justify-content: center;");
a("  font-size: 10.5px; font-weight: 800;");
a("  background: #E8EDEC; color: #9DBBB7;");
a("  flex-shrink: 0; transition: all 0.2s;");
a("}");
a(".step-item.active .step-num {");
a("  background: linear-gradient(135deg, var(--primary), var(--dark));");
a("  color: white; box-shadow: 0 2px 8px rgba(0,181,165,0.4);");
a("}");
a(".step-item.done .step-num { background: var(--mid); color: white; }");
a(".step-connector { width: 32px; height: 1px; background: var(--border); }");
a("");
a("/* ── LAYOUT ── */");
a(".app { min-height: 100vh; display: flex; flex-direction: column; }");
a(".page { flex: 1; }");
a("");
a("/* ── LANDING ── */");
a(".landing {");
a("  display: flex; flex-direction: column; align-items: center;");
a("  min-height: calc(100vh - 120px);");
a("  padding: 64px 24px 72px;");
a("  text-align: center;");
a("  background: radial-gradient(ellipse 80% 40% at 50% 0%, rgba(0,181,165,0.07) 0%, transparent 70%);");
a("}");
a(".landing-logo { height: 68px; width: auto; margin-bottom: 24px; filter: drop-shadow(0 2px 8px rgba(0,181,165,0.15)); }");
a(".landing-title {");
a("  font-size: 30px; font-weight: 900; color: var(--text);");
a("  letter-spacing: -0.5px; line-height: 1.2; margin-bottom: 12px;");
a("}");
a(".landing-sub {");
a("  font-size: 15px; color: var(--muted);");
a("  max-width: 420px; line-height: 1.8; margin-bottom: 32px;");
a("  font-weight: 400;");
a("}");
a(".btn-template { margin-bottom: 28px; }");
a("");
a("/* Upload box */");
a(".upload-box {");
a("  border: 2px dashed var(--border);");
a("  border-radius: var(--radius);");
a("  background: var(--white);");
a("  padding: 52px 64px;");
a("  cursor: pointer;");
a("  transition: border-color 0.2s, box-shadow 0.2s, background 0.2s;");
a("  width: 100%; max-width: 480px;");
a("  position: relative;");
a("}");
a(".upload-box:hover, .upload-box.dragging {");
a("  border-color: var(--primary);");
a("  background: linear-gradient(to bottom, rgba(0,181,165,0.03), rgba(0,181,165,0.01));");
a("  box-shadow: 0 0 0 4px rgba(0,181,165,0.08), var(--shadow);");
a("}");
a(".upload-box-icon {");
a("  width: 56px; height: 56px;");
a("  background: linear-gradient(135deg, rgba(0,181,165,0.12), rgba(0,122,110,0.08));");
a("  border-radius: 50%;");
a("  display: flex; align-items: center; justify-content: center;");
a("  margin: 0 auto 18px;");
a("  color: var(--primary);");
a("  transition: background 0.2s;");
a("}");
a(".upload-box:hover .upload-box-icon {");
a("  background: linear-gradient(135deg, var(--primary), var(--dark));");
a("  color: white;");
a("}");
a(".upload-box-title { font-size: 15px; font-weight: 700; color: var(--text); margin-bottom: 6px; }");
a(".upload-box-hint { font-size: 12.5px; color: var(--muted); line-height: 1.6; }");
a(".upload-box-types { margin-top: 18px; display: flex; gap: 6px; justify-content: center; }");
a(".file-type-tag {");
a("  background: var(--bg); color: var(--muted);");
a("  font-size: 9.5px; font-weight: 800;");
a("  padding: 3px 9px; border-radius: 5px;");
a("  border: 1px solid var(--border); letter-spacing: 0.8px; text-transform: uppercase;");
a("}");
a("");
a("/* File loaded state */");
a(".file-loaded-box {");
a("  width: 100%; max-width: 480px;");
a("  background: var(--white);");
a("  border-radius: var(--radius);");
a("  padding: 28px 32px;");
a("  display: flex; flex-direction: column; align-items: center; gap: 12px;");
a("  box-shadow: var(--shadow-md);");
a("  border-left: 4px solid var(--primary);");
a("}");
a(".file-loaded-icon {");
a("  color: var(--primary);");
a("  display: flex; align-items: center; justify-content: center;");
a("  width: 56px; height: 56px;");
a("  background: linear-gradient(135deg, rgba(0,181,165,0.12), rgba(0,122,110,0.08));");
a("  border-radius: 50%;");
a("}");
a(".file-loaded-info { text-align: center; }");
a(".file-loaded-name { font-size: 14px; font-weight: 700; color: var(--text); word-break: break-all; }");
a(".file-loaded-count { font-size: 12.5px; color: var(--muted); margin-top: 4px; font-weight: 500; }");
a(".file-loaded-actions { display: flex; gap: 10px; margin-top: 4px; width: 100%; justify-content: center; }");
a(".file-loaded-actions .btn-primary { flex: 1; max-width: 200px; }");
a("");
a("/* Feature row */");
a(".landing-features { display: flex; gap: 40px; margin-top: 52px; flex-wrap: wrap; justify-content: center; }");
a(".feature-item { display: flex; flex-direction: column; align-items: center; gap: 10px; max-width: 120px; }");
a(".feature-icon {");
a("  width: 44px; height: 44px; border-radius: 12px;");
a("  background: var(--white);");
a("  box-shadow: var(--shadow);");
a("  display: flex; align-items: center; justify-content: center;");
a("  color: var(--primary);");
a("}");
a(".feature-label { font-size: 11.5px; font-weight: 600; color: var(--muted); text-align: center; line-height: 1.5; }");
a("");
a("/* ── STATUS ── */");
a(".status-msg {");
a("  max-width: 480px; width: 100%; margin-top: 16px;");
a("  padding: 11px 16px; border-radius: var(--radius-sm);");
a("  font-size: 12.5px; font-weight: 500;");
a("  display: flex; align-items: flex-start; gap: 10px; line-height: 1.55;");
a("}");
a(".status-msg.success { background: #EDFBF0; color: #1B6B2F; border: 1px solid #B2E0BE; }");
a(".status-msg.error   { background: #FEF3F2; color: #B91C1C; border: 1px solid #FCA5A5; }");
a(".status-msg.info    { background: #EFF6FF; color: #1D4ED8; border: 1px solid #93C5FD; }");
a("");
a("/* ── REVIEW PAGE ── */");
a(".review-page { max-width: 1120px; margin: 0 auto; padding: 44px 36px 80px; }");
a(".review-header {");
a("  display: flex; align-items: center; gap: 20px;");
a("  margin-bottom: 32px; flex-wrap: wrap;");
a("}");
a(".review-back { flex-shrink: 0; }");
a(".review-header-text { flex: 1; min-width: 160px; }");
a(".review-title {");
a("  font-size: 22px; font-weight: 800; color: var(--text);");
a("  letter-spacing: -0.3px; margin-bottom: 3px;");
a("}");
a(".review-subtitle { font-size: 13px; color: var(--muted); line-height: 1.55; }");
a(".review-summary-pill {");
a("  background: linear-gradient(135deg, var(--primary), var(--dark));");
a("  color: white;");
a("  font-size: 12px; font-weight: 700;");
a("  padding: 8px 20px; border-radius: 999px;");
a("  display: flex; align-items: center; gap: 6px; flex-shrink: 0;");
a("  box-shadow: 0 2px 12px rgba(0,181,165,0.35);");
a("}");
a(".review-summary-num { font-size: 17px; font-weight: 900; line-height: 1; }");
a(".review-layout { display: grid; grid-template-columns: 1fr 310px; gap: 24px; align-items: start; }");
a(".review-right { position: sticky; top: 80px; display: flex; flex-direction: column; gap: 16px; }");
a("");
a("/* Table card */");
a(".review-table-card {");
a("  background: var(--white);");
a("  border-radius: var(--radius);");
a("  overflow: hidden;");
a("  box-shadow: var(--shadow);");
a("}");
a(".review-section-head {");
a("  padding: 16px 20px;");
a("  border-bottom: 1px solid var(--border);");
a("  display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 10px;");
a("}");
a(".review-section-title { font-size: 13px; font-weight: 700; color: var(--text); }");
a(".review-cols-row { display: flex; gap: 6px; flex-wrap: wrap; }");
a(".review-table-wrap { max-height: 430px; overflow-y: auto; }");
a(".review-table { width: 100%; border-collapse: collapse; font-size: 12.5px; }");
a(".review-table thead th {");
a("  background: linear-gradient(to bottom, var(--dark), #006860);");
a("  color: rgba(255,255,255,0.9);");
a("  padding: 11px 18px;");
a("  text-align: left;");
a("  font-size: 10.5px; font-weight: 700; letter-spacing: 0.8px; text-transform: uppercase;");
a("  position: sticky; top: 0; z-index: 1;");
a("}");
a(".review-table thead th.col-num { width: 44px; text-align: center; }");
a(".review-table tbody tr { transition: background 0.1s; }");
a(".review-table tbody tr:nth-child(even) td { background: #FAFFFE; }");
a(".review-table tbody tr:hover td { background: var(--light) !important; }");
a(".review-table td { padding: 9px 18px; border-bottom: 1px solid #F0F7F6; vertical-align: middle; }");
a(".review-table tr:last-child td { border-bottom: none; }");
a(".col-num-cell { text-align: center; color: var(--soft); font-size: 11px; font-weight: 500; }");
a(".code-badge {");
a("  display: inline-block;");
a("  background: linear-gradient(to right, rgba(0,181,165,0.08), rgba(0,122,110,0.06));");
a("  color: var(--dark);");
a("  font-family: 'SF Mono', 'Fira Code', 'Courier New', monospace;");
a("  font-weight: 700; font-size: 11.5px; letter-spacing: 1px;");
a("  padding: 4px 10px; border-radius: 6px;");
a("  border: 1px solid rgba(0,181,165,0.2);");
a("}");
a(".date-cell { color: var(--text); font-size: 12px; }");
a(".muted-cell { color: var(--soft); }");
a(".date-inherited { color: var(--mid); font-weight: 600; }");
a(".inherited-label {");
a("  display: inline-block; font-size: 9px;");
a("  background: var(--light); color: var(--mid);");
a("  border: 1px solid rgba(0,181,165,0.25); border-radius: 4px;");
a("  padding: 1px 5px; vertical-align: middle; margin-left: 4px;");
a("  font-weight: 700; letter-spacing: 0.4px;");
a("}");
a(".more-row td { text-align: center; color: var(--soft); font-style: italic; padding: 12px; font-size: 11px; }");
a(".review-table-footer {");
a("  padding: 10px 20px; border-top: 1px solid var(--border);");
a("  display: flex; gap: 20px; font-size: 11px; color: var(--muted); font-weight: 500;");
a("  background: #FAFFFE; flex-wrap: wrap;");
a("}");
a(".warn-text { color: #C2660A; }");
a("");
a("/* Config cards */");
a(".config-card {");
a("  background: var(--white);");
a("  border-radius: var(--radius);");
a("  overflow: hidden;");
a("  box-shadow: var(--shadow);");
a("}");
a(".config-card-head {");
a("  display: flex; align-items: center; gap: 12px;");
a("  padding: 16px 20px;");
a("  border-bottom: 1px solid var(--border);");
a("}");
a(".config-card-icon {");
a("  width: 34px; height: 34px; border-radius: 9px;");
a("  background: var(--light); color: var(--dark);");
a("  display: flex; align-items: center; justify-content: center; flex-shrink: 0;");
a("}");
a(".config-card-icon.accent {");
a("  background: linear-gradient(135deg, var(--primary), var(--dark));");
a("  color: white; box-shadow: 0 2px 8px rgba(0,181,165,0.35);");
a("}");
a(".config-card-title { font-size: 13.5px; font-weight: 700; color: var(--text); margin-bottom: 2px; }");
a(".config-card-sub { font-size: 11px; color: var(--muted); line-height: 1.45; }");
a(".config-card-body { padding: 18px 20px 20px; }");
a(".form-row { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; }");
a(".generate-card {");
a("  border: none;");
a("  background: var(--white);");
a("  box-shadow: 0 2px 8px rgba(0,181,165,0.12), 0 0 0 1.5px rgba(0,181,165,0.25);");
a("}");
a(".generate-btn { font-size: 13.5px; padding: 13px 22px; border-radius: 999px; gap: 8px; letter-spacing: 0.2px; }");
a(".generate-progress { margin-top: 12px; }");
a("");
a("/* ── CARDS PAGE ── */");
a(".cards-page { max-width: 1200px; margin: 0 auto; padding: 40px 36px 64px; }");
a(".cards-toolbar {");
a("  display: flex; align-items: center; gap: 14px;");
a("  margin-bottom: 32px; flex-wrap: wrap;");
a("  padding-bottom: 20px; border-bottom: 1px solid var(--border);");
a("}");
a(".cards-toolbar-left { flex: 1; }");
a(".page-heading { font-size: 20px; font-weight: 800; color: var(--text); letter-spacing: -0.3px; margin-bottom: 4px; }");
a(".cards-count {");
a("  display: inline-flex; align-items: center;");
a("  background: linear-gradient(135deg, rgba(0,181,165,0.1), rgba(0,122,110,0.07));");
a("  color: var(--dark); font-size: 11.5px; font-weight: 700;");
a("  border-radius: 999px; padding: 4px 14px;");
a("  border: 1px solid rgba(0,181,165,0.2);");
a("}");
a(".cards-toolbar-actions { display: flex; gap: 10px; align-items: center; flex-wrap: wrap; }");
a(".divider-v { width: 1px; height: 24px; background: var(--border); }");
a(".preview-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(290px, 1fr)); gap: 22px; }");
a(".preview-wrapper {");
a("  background: var(--white); border-radius: var(--radius);");
a("  overflow: hidden; box-shadow: var(--shadow);");
a("  transition: box-shadow 0.22s, transform 0.18s;");
a("}");
a(".preview-wrapper:hover { box-shadow: var(--shadow-md); transform: translateY(-3px); }");
a(".preview-scale-outer { overflow: hidden; width: 100%; position: relative; }");
a(".preview-footer {");
a("  background: #FAFFFE; border-top: 1px solid var(--border);");
a("  padding: 11px 14px; display: flex;");
a("  align-items: center; justify-content: space-between; gap: 8px;");
a("}");
a(".preview-code-label {");
a("  font-size: 11px; font-weight: 700; color: var(--muted);");
a("  font-family: 'SF Mono', 'Fira Code', monospace; letter-spacing: 0.8px;");
a("  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 155px;");
a("}");
a(".download-btns { display: flex; gap: 6px; }");
a("");
a("/* ── FORM ── */");
a(".form-group { display: flex; flex-direction: column; gap: 6px; }");
a(".form-label { font-size: 10.5px; font-weight: 700; color: var(--muted); letter-spacing: 0.6px; text-transform: uppercase; }");
a(".form-input {");
a("  border: 1.5px solid var(--border); border-radius: var(--radius-sm);");
a("  padding: 10px 13px; font-size: 13px; color: var(--text);");
a("  font-family: inherit; outline: none; background: var(--white);");
a("  width: 100%; transition: border-color 0.15s, box-shadow 0.15s;");
a("}");
a(".form-input:focus { border-color: var(--primary); box-shadow: 0 0 0 3px rgba(0,181,165,0.12); }");
a(".form-hint { font-size: 11.5px; color: var(--muted); line-height: 1.55; margin-bottom: 4px; }");
a(".form-divider { height: 1px; background: var(--border); margin: 14px 0; }");
a("");
a("/* ── BUTTONS ── */");
a(".btn {");
a("  display: inline-flex; align-items: center; justify-content: center;");
a("  gap: 7px; border: none; border-radius: 999px;");
a("  font-size: 13px; font-weight: 700; font-family: inherit;");
a("  cursor: pointer; letter-spacing: 0.15px; white-space: nowrap;");
a("  padding: 10px 22px;");
a("  transition: all 0.18s;");
a("}");
a(".btn:disabled { opacity: 0.4; cursor: not-allowed; transform: none !important; box-shadow: none !important; }");
a(".btn-primary {");
a("  background: linear-gradient(135deg, var(--primary) 0%, var(--dark) 100%);");
a("  color: white;");
a("  box-shadow: 0 3px 12px rgba(0,181,165,0.35);");
a("}");
a(".btn-primary:hover:not(:disabled) { box-shadow: 0 5px 20px rgba(0,181,165,0.5); transform: translateY(-1px); filter: brightness(1.05); }");
a(".btn-secondary {");
a("  background: var(--white); color: var(--dark);");
a("  border: 1.5px solid var(--border);");
a("  box-shadow: 0 1px 4px rgba(0,0,0,0.05);");
a("}");
a(".btn-secondary:hover:not(:disabled) { border-color: var(--primary); background: var(--light); color: var(--dark); box-shadow: 0 2px 8px rgba(0,181,165,0.15); }");
a(".btn-accent {");
a("  background: linear-gradient(135deg, var(--mid) 0%, var(--primary) 100%);");
a("  color: white; box-shadow: 0 3px 12px rgba(0,181,165,0.3);");
a("}");
a(".btn-accent:hover:not(:disabled) { transform: translateY(-1px); box-shadow: 0 5px 20px rgba(0,181,165,0.45); filter: brightness(1.05); }");
a(".btn-outline {");
a("  background: transparent; color: var(--dark);");
a("  border: 1.5px solid var(--border);");
a("}");
a(".btn-outline:hover:not(:disabled) { border-color: var(--primary); background: var(--light); }");
a(".btn-ghost {");
a("  background: transparent; color: var(--muted);");
a("  border: 1.5px solid var(--border);");
a("  padding: 8px 16px; font-size: 12px; border-radius: 999px;");
a("}");
a(".btn-ghost:hover:not(:disabled) { background: var(--light); color: var(--dark); border-color: var(--primary); }");
a(".btn-sm { padding: 6px 16px; font-size: 11.5px; }");
a(".btn-full { width: 100%; border-radius: var(--radius-sm); }");
a(".btn-full.generate-btn { border-radius: 999px; }");
a("");
a("/* ── PROGRESS ── */");
a(".progress-wrap {");
a("  background: var(--border); border-radius: 99px;");
a("  height: 5px; overflow: hidden; margin: 8px 0 4px;");
a("}");
a(".progress-bar {");
a("  height: 100%;");
a("  background: linear-gradient(90deg, var(--primary), var(--dark));");
a("  border-radius: 99px; transition: width 0.3s ease;");
a("}");
a(".progress-label { font-size: 11px; color: var(--muted); text-align: right; font-weight: 500; }");
a("");
a("/* ── SPINNER ── */");
a(".spinner {");
a("  display: inline-block; width: 13px; height: 13px;");
a("  border: 2px solid rgba(255,255,255,0.3); border-top-color: white;");
a("  border-radius: 50%; animation: spin 0.65s linear infinite; flex-shrink: 0;");
a("}");
a(".spinner-dark { border-color: rgba(0,122,110,0.2); border-top-color: var(--primary); }");
a("@keyframes spin { to { transform: rotate(360deg); } }");
a("");
a("/* ── CHIPS ── */");
a(".col-chip {");
a("  display: inline-flex; align-items: center; gap: 5px;");
a("  background: var(--bg); border: 1px solid var(--border);");
a("  border-radius: 999px; padding: 3px 11px;");
a("  font-size: 10.5px; color: var(--text); font-weight: 600;");
a("}");
a(".col-chip-label { color: var(--soft); font-weight: 400; }");
a("");
a("/* ── HIDDEN RENDER ── */");
a(".hidden-render { position: fixed; left: -99999px; top: 0; pointer-events: none; z-index: -1; }");
a("");
a("/* ── LEGACY ── */");
a(".card-panel { background: var(--white); border-radius: var(--radius); overflow: hidden; box-shadow: var(--shadow); }");
a(".card-panel-header {");
a("  background: linear-gradient(to bottom, var(--dark), #006860);");
a("  color: rgba(255,255,255,0.9);");
a("  padding: 12px 18px; font-size: 10.5px; font-weight: 700; letter-spacing: 0.8px; text-transform: uppercase;");
a("  display: flex; align-items: center; justify-content: space-between;");
a("}");
a(".card-panel-body { padding: 20px; }");
a("");
a("/* ── RESPONSIVE ── */");
a("@media (max-width: 768px) {");
a("  .topnav { padding: 0 20px; }");
a("  .review-page, .cards-page { padding: 28px 18px 48px; }");
a("  .review-layout { grid-template-columns: 1fr; }");
a("  .review-right { position: static; }");
a("  .preview-grid { grid-template-columns: 1fr 1fr; }");
a("  .landing { padding: 44px 18px 52px; }");
a("  .upload-box { padding: 40px 28px; }");
a("  .landing-title { font-size: 24px; }");
a("}");
a("@media (max-width: 500px) {");
a("  .preview-grid { grid-template-columns: 1fr; }");
a("  .landing-features { gap: 24px; }");
a("  .review-layout { grid-template-columns: 1fr; }");
a("}");

fs.writeFileSync('src/App.css', lines.join('\n'), { encoding: 'utf8' });
console.log('Done. Lines:', lines.length, '  Bytes:', Buffer.byteLength(lines.join('\n')));
